### ISSUE TITLE
PM09 Issue #2

### ISSUE THREAD

**Issue by efforgety** [Milligan-Engineering/Hilt#10]
Issue two is similar to Issue one. The second user prompt is to enter the number of students, and it says not to enter over 100. When I entered a value greater than 100, the program continues as normal. Maybe you could add a do-while as a fail-safe for this.

**Comment by weasal** [comment]
It will now loop for this input if greater than 100 instead of accepting it.  I will work on refining the UI language soon as it is still a bit rough.
