### ISSUE TITLE
PM09 #3

### ISSUE THREAD

**Issue by efforgety** [Milligan-Engineering/Hilt#11]
This one is a bit of a stretch. For the user prompt asking for a estimate of total number of files, it asks you to type "y for yes or any other letter for no." This works great when the user only enters one letter and hits enter. However, as a user who may misread the instructions and type ""yes" or accidentally type more than one letter, the program attempts to use the following letters as inputs for the next user prompt, giving the user a couple confusing error messages indicating improper input for the "how many files" prompt.

**Comment by weasal** [comment]
Changed it so that it will read the first character of input to allow words to be used in place of just characters for these types of inputs.
